name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t auladesoftwarelibre/api-image:${{ github.sha }} .
        docker save auladesoftwarelibre/api-image:${{ github.sha }} | gzip > my-image.tar.gz

    - name: Transfer Docker image to server
      run: |
        scp -o StrictHostKeyChecking=no my-image.tar.gz user@server:/destination/path
      env:
        SSH_PASS: ${{ secrets.SSH_PASS }}

    - name: Clean up
      run: |
        rm my-image.tar.gz
